---
- hosts: dev
  gather_facts: no
  vars:
    src_path: "/var/lib/jenkins/workspace/demooo/target"
    des_path: "/root/"
  tasks:
  - name: Ansible copy files remote to remote
    shell: 'cp -r {{ src_path }}/CounterWebApp.war {{ des_path }}'

